#   uv run --group catboost python exps/bars/train.py \
#       --config exps/bars/configs/config_catboost_criteo_x1.yaml
model: catboost
dataset: criteo_x1
num_features: [I1, I2, I3, I4, I5, I6, I7, I8, I9, I10, I11, I12, I13]
cat_features: [C1, C2, C3, C4, C5, C6, C7, C8, C9, C10, C11, C12, C13, C14, C15, C16, C17, C18, C19, C20, C21, C22, C23, C24, C25, C26]
data_dir: data/Criteo_x1
max_train_rows: null
verbose: false

model_params:
  task_type: CPU
  use_best_model: true
  allow_writing_files: false
  random_seed: 2021
  loss_function: Logloss
  eval_metric: AUC
  early_stopping_rounds: 200
  iterations: 1000
  learning_rate: 0.35
  depth: 9
  l2_leaf_reg: 20
  random_strength: 0.0
  model_size_reg: 0.5
  bootstrap_type: MVS
  subsample: 0.8
  rsm: 1.0
  max_ctr_complexity: 4
  one_hot_max_size: 2
  border_count: 254
  thread_count: -1
